
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUREASIGN ASIGN EQ EQ2 ID N PR PR RE RPT RPT SU Vresultado : sresultado : ASIGN ID EQ EQ2 ss : Ns : IDs : s SU s\n        | s RE ss : PR ID \n    | PR s'
    
_lr_action_items = {'ASIGN':([0,],[3,]),'N':([0,6,7,8,15,],[5,5,5,5,5,]),'ID':([0,3,6,7,8,15,],[4,9,10,4,4,4,]),'PR':([0,6,7,8,15,],[6,6,6,6,6,]),'$end':([1,2,4,5,10,11,12,13,16,],[0,-1,-4,-3,-4,-8,-5,-6,-2,]),'SU':([2,4,5,10,11,12,13,16,],[7,-4,-3,-4,7,-5,-6,7,]),'RE':([2,4,5,10,11,12,13,16,],[8,-4,-3,-4,8,-5,-6,8,]),'EQ':([9,],[14,]),'EQ2':([14,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'resultado':([0,],[1,]),'s':([0,6,7,8,15,],[2,11,12,13,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> resultado","S'",1,None,None,None),
  ('resultado -> s','resultado',1,'p_resultado','Interpreter.py',62),
  ('resultado -> ASIGN ID EQ EQ2 s','resultado',5,'p_asignacion','Interpreter.py',66),
  ('s -> N','s',1,'p_expr_num','Interpreter.py',70),
  ('s -> ID','s',1,'p_expr_id','Interpreter.py',74),
  ('s -> s SU s','s',3,'p_expr_op','Interpreter.py',82),
  ('s -> s RE s','s',3,'p_expr_op','Interpreter.py',83),
  ('s -> PR ID','s',2,'p_PR','Interpreter.py',93),
  ('s -> PR s','s',2,'p_PR','Interpreter.py',94),
]
